package pojo;
// Generated May 13, 2020 7:01:43 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Checkinout generated by hbm2java
 */
public class Checkinout  implements java.io.Serializable {


     private String bookId;
     private String regno;
     private String bookTitle;
     private Date datetime;

    public Checkinout() {
    }

    public Checkinout(String bookId, String regno, String bookTitle, Date datetime) {
       this.bookId = bookId;
       this.regno = regno;
       this.bookTitle = bookTitle;
       this.datetime = datetime;
    }
   
    public String getBookId() {
        return this.bookId;
    }
    
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }
    public String getRegno() {
        return this.regno;
    }
    
    public void setRegno(String regno) {
        this.regno = regno;
    }
    public String getBookTitle() {
        return this.bookTitle;
    }
    
    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }




}


