package pojo;
// Generated May 13, 2020 7:01:43 AM by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private String regNo;
     private Clientcategory clientcategory;
     private String firstName;
     private String lastName;
     private String phoneNumber;
     private String email;
     private String photo;

    public Client() {
    }

	
    public Client(String regNo) {
        this.regNo = regNo;
    }
    public Client(String regNo, Clientcategory clientcategory, String firstName, String lastName, String phoneNumber, String email, String photo) {
       this.regNo = regNo;
       this.clientcategory = clientcategory;
       this.firstName = firstName;
       this.lastName = lastName;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.photo = photo;
    }
   
    public String getRegNo() {
        return this.regNo;
    }
    
    public void setRegNo(String regNo) {
        this.regNo = regNo;
    }
    public Clientcategory getClientcategory() {
        return this.clientcategory;
    }
    
    public void setClientcategory(Clientcategory clientcategory) {
        this.clientcategory = clientcategory;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }




}


