package pojo;
// Generated May 13, 2020 7:01:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientcategory generated by hbm2java
 */
public class Clientcategory  implements java.io.Serializable {


     private String categoryName;
     private String categoryId;
     private Set clients = new HashSet(0);

    public Clientcategory() {
    }

	
    public Clientcategory(String categoryName) {
        this.categoryName = categoryName;
    }
    public Clientcategory(String categoryName, String categoryId, Set clients) {
       this.categoryName = categoryName;
       this.categoryId = categoryId;
       this.clients = clients;
    }
   
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }




}


