package pojo;
// Generated May 13, 2020 7:01:43 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private String username;
     private String password;
     private String firstName;
     private String lastName;
     private Date dob;

    public Login() {
    }

	
    public Login(String username) {
        this.username = username;
    }
    public Login(String username, String password, String firstName, String lastName, Date dob) {
       this.username = username;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.dob = dob;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }




}


